sonar.projectKey=ncovachAJS_conciertos_app
sonar.projectName=Conciertos App
sonar.projectVersion=1.0
sonar.organization=ncovachajs-1

# Fuentes
sonar.sources=lib
sonar.tests=test

# Exclusiones — código generado, assets, firebase
sonar.exclusions=\
  lib/**/*.g.dart,\
  lib/firebase_options.dart,\
  lib/l10n/generated/**,\
  lib/**/setlist_test_page.dart

sonar.test.exclusions=\
  test/widget_test.dart,\
  test/integration_test.dart

# Cobertura (generada por flutter test --coverage)
sonar.dart.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=\
  lib/**/*.g.dart,\
  lib/firebase_options.dart,\
  lib/l10n/generated/**,\
  lib/**/setlist_test_page.dart,\
  lib/main.dart,\
  lib/app/app.dart,\
  lib/app/router.dart

# Encoding
sonar.sourceEncoding=UTF-8
