// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDviJ7_SaP6K_3OGdKlcdR8uXMq2cYsMRw',
    appId: '1:988375120062:web:6bb4da8dd56419cf6106ef',
    messagingSenderId: '988375120062',
    projectId: 'la-vida-en-directo',
    authDomain: 'la-vida-en-directo.firebaseapp.com',
    storageBucket: 'la-vida-en-directo.firebasestorage.app',
    measurementId: 'G-85L1Z5XQRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ1UdY8ve5VRPlLxZHYvL1LnfWJFZZnag',
    appId: '1:988375120062:android:a8b1cee2618d81656106ef',
    messagingSenderId: '988375120062',
    projectId: 'la-vida-en-directo',
    storageBucket: 'la-vida-en-directo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7MmkPANyozE4lu9WFWqq0cl1w38iP-dk',
    appId: '1:988375120062:ios:9d1ac6bc57243a956106ef',
    messagingSenderId: '988375120062',
    projectId: 'la-vida-en-directo',
    storageBucket: 'la-vida-en-directo.firebasestorage.app',
    iosBundleId: 'com.example.conciertosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7MmkPANyozE4lu9WFWqq0cl1w38iP-dk',
    appId: '1:988375120062:ios:9d1ac6bc57243a956106ef',
    messagingSenderId: '988375120062',
    projectId: 'la-vida-en-directo',
    storageBucket: 'la-vida-en-directo.firebasestorage.app',
    iosBundleId: 'com.example.conciertosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDviJ7_SaP6K_3OGdKlcdR8uXMq2cYsMRw',
    appId: '1:988375120062:web:5e763fe2645ac19e6106ef',
    messagingSenderId: '988375120062',
    projectId: 'la-vida-en-directo',
    authDomain: 'la-vida-en-directo.firebaseapp.com',
    storageBucket: 'la-vida-en-directo.firebasestorage.app',
    measurementId: 'G-32PGD2EKZX',
  );
}
