const countries = {
  'Todo el mundo': '',
  'España': 'ES',
  'Portugal': 'PT',
  'Francia': 'FR',
  'Reino Unido': 'GB',
  'Alemania': 'DE',
  'Italia': 'IT',
  'Países Bajos': 'NL',
  'Bélgica': 'BE',
  'Suiza': 'CH',
  'Austria': 'AT',
  'Polonia': 'PL',
  'República Checa': 'CZ',
  'Argentina': 'AR',
  'Chile': 'CL',
  'Uruguay': 'UY',
  'Brasil': 'BR',
  'México': 'MX',
  'Estados Unidos': 'US',
  'Canadá': 'CA',
  'Japón': 'JP',
  'Australia': 'AU',
};
